services:
  postgres:
    image: postgres:16-alpine
    restart: always

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres-data:/var/lib/postgresql/data

  migrations:
    image: ghcr.io/ravichanduri/mynotes-migrations:latest

    environment:
      ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}

    depends_on:
      postgres:
        condition: service_healthy

  api:
    image: ghcr.io/ravichanduri/mynotes-api:latest

    restart: always

    environment:
      ASPNETCORE_ENVIRONMENT: Production

      ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}

      Jwt__Key: ${JWT_KEY}

    ports:
      - "8080:8080"

  web:
    image: ghcr.io/ravichanduri/mynotes-web:latest

    restart: always

    ports:
      - "80:80"

volumes:
  postgres-data: