import { useEffect, useState } from 'react';
import { Alert, AppBar, Box, Button, Card, CardActions, CardContent, Container, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, Stack, TextField, Toolbar, Typography } from '@mui/material';
import DeleteIcon from '@mui/icons-material/Delete';
import Calculator from "./Calculator";

type Note = { id: string; title: string; content: string; isFavorite: boolean };
const api = async <T,>(path: string, init?: RequestInit): Promise<T> => { const token = localStorage.getItem('accessToken'); const response = await fetch(`/api${path}`, { ...init, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...init?.headers } }); if (!response.ok) throw new Error(response.status === 401 ? 'Please sign in.' : 'Request failed.'); return response.status === 204 ? undefined as T : response.json() as Promise<T>; };

export default function App() {
  return <Calculator />;
  // const [notes, setNotes] = useState<Note[]>([]); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [open, setOpen] = useState(false); const [draft, setDraft] = useState({ title: '', content: '' });
  // const load = () => api<Note[]>('/notes').then(setNotes).catch(e => setError(e.message));
  // useEffect(() => { if (localStorage.getItem('accessToken')) load(); }, []);
  // const login = async () => { try { const result = await api<{ accessToken: string }>('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); localStorage.setItem('accessToken', result.accessToken); setError(''); load(); } catch (e) { setError((e as Error).message); } };
  // const save = async () => { await api<Note>('/notes', { method: 'POST', body: JSON.stringify({ ...draft, isFavorite: false }) }); setOpen(false); setDraft({ title: '', content: '' }); load(); };
  // const remove = async (id: string) => { await api(`/notes/${id}`, { method: 'DELETE' }); load(); };
  // if (!localStorage.getItem('accessToken')) return <Container maxWidth="sm" sx={{ pt: 12 }}><Stack spacing={2}><Typography variant="h4">Notes Hub Yashwanth</Typography><Typography color="text.secondary">Please Sign in to your workspace</Typography>{error && <Alert severity="error">{error}</Alert>}<TextField label="Email" value={email} onChange={e => setEmail(e.target.value)} /><TextField label="Password" type="password" value={password} onChange={e => setPassword(e.target.value)} /><Button variant="contained" onClick={login}>Sign in</Button></Stack></Container>;
  // return <><AppBar position="static"><Toolbar><Typography variant="h6" sx={{ flexGrow: 1 }}>Notes Hub For Chanduri</Typography><Button color="inherit" onClick={() => { localStorage.removeItem('accessToken'); location.reload(); }}>Sign out</Button></Toolbar></AppBar><Container sx={{ py: 4 }}><Stack direction="row" justifyContent="space-between" alignItems="center" mb={3}><Typography variant="h4">My notes</Typography><Button variant="contained" onClick={() => setOpen(true)}>New note</Button></Stack>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<Box display="grid" gridTemplateColumns="repeat(auto-fill, minmax(260px, 1fr))" gap={2}>{notes.map(note => <Card key={note.id}><CardContent><Typography variant="h6">{note.title}</Typography><Typography whiteSpace="pre-wrap">{note.content}</Typography></CardContent><CardActions><IconButton aria-label="Delete note" onClick={() => remove(note.id)}><DeleteIcon /></IconButton></CardActions></Card>)}</Box></Container><Dialog open={open} onClose={() => setOpen(false)} fullWidth><DialogTitle>New note</DialogTitle><DialogContent><Stack sx={{ pt: 1 }} spacing={2}><TextField label="Title" value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} /><TextField label="Content" multiline minRows={5} value={draft.content} onChange={e => setDraft({ ...draft, content: e.target.value })} /></Stack></DialogContent><DialogActions><Button onClick={() => setOpen(false)}>Cancel</Button><Button onClick={save} variant="contained">Save</Button></DialogActions></Dialog></>;
}
